### ISSUE TITLE
!msync getver triggers traceback

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/thevoxfox#1]
The above mentioned command fails with:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/Legobot/Lego.py", line 26, in run
    self.handler(self.message)
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/Legobot/Connectors/IRC.py", line 103,
 in handle                                                                                                    self.botThread.connection.privmsg(message['metadata']['opts']['target'], message['text'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bbriggs** [comment]
That's probably from some bad metadata. I'll take a look at that later tonight.

**Comment by bastelfreak** [comment]
now I get:

```
2016-11-19 16:46:31,726 - Legobot.Connectors.IRC - INFO - {'should_log': False, 'text': 'womp womp :/ unable to get version.', 'metadata': {'dest': <IRCBot(Thread-2, started 140396652365568)>, 'opts': {'target': '#voxpupuli'}, 'source': <Local.Msync.Audit object at 0x7fb0a5981470>}}
2016-11-19 16:46:31,723 - Local.Msync - ERROR - Caught exception in !msync:list index out of range
Traceback (most recent call last):
  File "/home/bastelfreak/thevoxfox/Local/Msync.py", line 29, in handle
    modname = message['text'].split()[2]
IndexError: list index out of range
```

**Comment by bastelfreak** [comment]
I was using it wrong, the correct commands are `!msync` or `!msync getver $modulename`. Both are working.
