### ISSUE TITLE
failes with UTF8?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/thevoxfox#15]
I've no idea whats happening:

```
2016-11-27 10:30:56,124 - irc.client - DEBUG - _dispatcher: pubmsg
2016-11-27 10:30:56,124 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Lego (urn:uuid:6efe5747-b705-42b4-ac88-a52fecb6320a)
2016-11-27 10:30:56,125 - Legobot.Lego - DEBUG - Acquired lock in cleanup for IRC (urn:uuid:6c4f6f2b-4fb8-43b4-b38a-145df8f97cdc)
2016-11-27 10:30:56,126 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Audit (urn:uuid:b1e90b4f-eabd-4c11-be29-4c798608d099)
2016-11-27 10:30:56,126 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Roll (urn:uuid:ca376c6d-3a05-47af-af0f-5b0f52b6b241)
2016-11-27 10:30:56,126 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Factoids (urn:uuid:1a2c0f03-31cc-4390-8f63-87b10fbd0cb6)
2016-11-27 10:30:56,127 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Puppet3 (urn:uuid:b5f2d7d8-8d1d-499f-9317-93bebf6fa836)
2016-11-27 10:30:56,127 - Legobot.Lego - DEBUG - Acquired lock in cleanup for WikipediaTopFinder (urn:uuid:7d2de64f-f705-44f7-8dcb-09c02511f51f)
2016-11-27 10:30:56,127 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Help (urn:uuid:e87679f9-9bb3-4afb-868e-87ecea967f6c)
2016-11-27 10:31:01,246 - jaraco.stream.buffer - WARNING -
Unknown encoding encountered. See 'Decoding Input'
in https://pypi.python.org/pypi/irc for details.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/Legobot/Connectors/IRC.py", line 87, in run
    super(irc.bot.SingleServerIRCBot, self).start()
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/irc/client.py", line 1247, in start
    self.reactor.process_forever()
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/irc/client.py", line 271, in process_forever
    consume(infinite_call(one))
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/more_itertools/recipes.py", line 90, in consume
    deque(iterator, maxlen=0)
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/jaraco/itertools.py", line 386, in <genexpr>
    return (f() for _ in itertools.repeat(None))
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/irc/client.py", line 252, in process_once
    self.process_data(i)
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/irc/client.py", line 577, in process_data
    for line in self.buffer:
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/jaraco/stream/buffer.py", line 104, in lines
    self.handle_exception()
  File "/home/bastelfreak/thevoxfox/venv/lib/python3.4/site-packages/jaraco/stream/buffer.py", line 102, in lines
    yield line.decode(self.encoding, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 96: invalid start byte
```

**Comment by sacres** [comment]
Perhaps we can close this as the 'fix' was merged @bastelfreak ?

**Comment by bastelfreak** [comment]
ah right
